# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/mambi/Jeux/PC/Tsui no Sora Remake/pfs_upk/pfs_upk"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/mambi/Jeux/PC/Tsui no Sora Remake/pfs_upk/pfs_upk"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/mambi/Jeux/PC/Tsui no Sora Remake/pfs_upk/pfs_upk/CMakeFiles" "/mnt/c/Users/mambi/Jeux/PC/Tsui no Sora Remake/pfs_upk/pfs_upk/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/mambi/Jeux/PC/Tsui no Sora Remake/pfs_upk/pfs_upk/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pfs_upk

# Build rule for target.
pfs_upk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfs_upk
.PHONY : pfs_upk

# fast build rule for target.
pfs_upk/fast:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/build
.PHONY : pfs_upk/fast

MemoryStream.o: MemoryStream.cpp.o

.PHONY : MemoryStream.o

# target to build an object file
MemoryStream.cpp.o:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/MemoryStream.cpp.o
.PHONY : MemoryStream.cpp.o

MemoryStream.i: MemoryStream.cpp.i

.PHONY : MemoryStream.i

# target to preprocess a source file
MemoryStream.cpp.i:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/MemoryStream.cpp.i
.PHONY : MemoryStream.cpp.i

MemoryStream.s: MemoryStream.cpp.s

.PHONY : MemoryStream.s

# target to generate assembly for a file
MemoryStream.cpp.s:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/MemoryStream.cpp.s
.PHONY : MemoryStream.cpp.s

pack.o: pack.cpp.o

.PHONY : pack.o

# target to build an object file
pack.cpp.o:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/pack.cpp.o
.PHONY : pack.cpp.o

pack.i: pack.cpp.i

.PHONY : pack.i

# target to preprocess a source file
pack.cpp.i:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/pack.cpp.i
.PHONY : pack.cpp.i

pack.s: pack.cpp.s

.PHONY : pack.s

# target to generate assembly for a file
pack.cpp.s:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/pack.cpp.s
.PHONY : pack.cpp.s

pfs_upk.o: pfs_upk.cpp.o

.PHONY : pfs_upk.o

# target to build an object file
pfs_upk.cpp.o:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/pfs_upk.cpp.o
.PHONY : pfs_upk.cpp.o

pfs_upk.i: pfs_upk.cpp.i

.PHONY : pfs_upk.i

# target to preprocess a source file
pfs_upk.cpp.i:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/pfs_upk.cpp.i
.PHONY : pfs_upk.cpp.i

pfs_upk.s: pfs_upk.cpp.s

.PHONY : pfs_upk.s

# target to generate assembly for a file
pfs_upk.cpp.s:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/pfs_upk.cpp.s
.PHONY : pfs_upk.cpp.s

sha1.o: sha1.c.o

.PHONY : sha1.o

# target to build an object file
sha1.c.o:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/sha1.c.o
.PHONY : sha1.c.o

sha1.i: sha1.c.i

.PHONY : sha1.i

# target to preprocess a source file
sha1.c.i:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/sha1.c.i
.PHONY : sha1.c.i

sha1.s: sha1.c.s

.PHONY : sha1.s

# target to generate assembly for a file
sha1.c.s:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/sha1.c.s
.PHONY : sha1.c.s

unpack.o: unpack.cpp.o

.PHONY : unpack.o

# target to build an object file
unpack.cpp.o:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/unpack.cpp.o
.PHONY : unpack.cpp.o

unpack.i: unpack.cpp.i

.PHONY : unpack.i

# target to preprocess a source file
unpack.cpp.i:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/unpack.cpp.i
.PHONY : unpack.cpp.i

unpack.s: unpack.cpp.s

.PHONY : unpack.s

# target to generate assembly for a file
unpack.cpp.s:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/unpack.cpp.s
.PHONY : unpack.cpp.s

xorcrypt.o: xorcrypt.cpp.o

.PHONY : xorcrypt.o

# target to build an object file
xorcrypt.cpp.o:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/xorcrypt.cpp.o
.PHONY : xorcrypt.cpp.o

xorcrypt.i: xorcrypt.cpp.i

.PHONY : xorcrypt.i

# target to preprocess a source file
xorcrypt.cpp.i:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/xorcrypt.cpp.i
.PHONY : xorcrypt.cpp.i

xorcrypt.s: xorcrypt.cpp.s

.PHONY : xorcrypt.s

# target to generate assembly for a file
xorcrypt.cpp.s:
	$(MAKE) -f CMakeFiles/pfs_upk.dir/build.make CMakeFiles/pfs_upk.dir/xorcrypt.cpp.s
.PHONY : xorcrypt.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pfs_upk"
	@echo "... MemoryStream.o"
	@echo "... MemoryStream.i"
	@echo "... MemoryStream.s"
	@echo "... pack.o"
	@echo "... pack.i"
	@echo "... pack.s"
	@echo "... pfs_upk.o"
	@echo "... pfs_upk.i"
	@echo "... pfs_upk.s"
	@echo "... sha1.o"
	@echo "... sha1.i"
	@echo "... sha1.s"
	@echo "... unpack.o"
	@echo "... unpack.i"
	@echo "... unpack.s"
	@echo "... xorcrypt.o"
	@echo "... xorcrypt.i"
	@echo "... xorcrypt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

